// Generates the thin route shells that make each registry record a real
// directory on the static host — services/<slug>/ and offers/<slug>/ — and
// refreshes their blocks in sitemap.xml.
//
// There is no build step for the site; this is a content tool, run once
// after a service or offer is added, renamed or retired:
//
//   node tools/build-routes.mjs
//
// Every shell is identical apart from the slug and its static <title>,
// description and canonical (so search engines see them without script);
// the page itself is drawn at runtime by one template module per
// collection. Do not edit a generated shell by hand — change the template.

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { SERVICE_REGISTRY } from '../assets/js/data/services.js';
import { OFFER_REGISTRY } from '../assets/js/data/offers.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://mashhorfoods.github.io/mashhor-demo/';
const TODAY = new Date().toISOString().slice(0, 10);
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');

/* One collection = one directory, one template module, one set of mount
   points. `sections` is the list of [data-<attr>="…"] sections the template
   fills; a section without content is hidden by the template. */
const COLLECTIONS = [
  {
    dir: 'services', records: SERVICE_REGISTRY, attr: 'detail', mount: 'mountServiceDetail', handle: 'detail',
    title: (s) => s.titleAr, description: (s) => s.descAr, og: (s) => s.shortAr, heroLabel: 'service-title', current: 'services',
    sections: ['overview', 'features', 'benefits', 'steps', 'requirements', 'related', 'support'],
  },
  {
    dir: 'offers', records: OFFER_REGISTRY, attr: 'offer', mount: 'mountOfferDetail', handle: 'offer',
    title: (o) => o.titleAr, description: (o) => o.shortAr, og: (o) => o.shortAr, heroLabel: 'offer-title', current: 'offers',
    sections: ['overview', 'included', 'excluded', 'itinerary', 'important', 'terms', 'faq', 'flow', 'related', 'support'],
  },
];

const shell = (c, r) => `<!doctype html>
<html lang="ar" dir="rtl" class="no-js">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- GENERATED by tools/build-routes.mjs — do not edit by hand. Two levels
     down, so <base> points every relative URL at the site root; in-page
     moves go through script, never href="#…". -->
<base href="../../">
<title>${esc(c.title(r))} — نمبرون للسفر و السياحة</title>
<meta name="description" content="${esc(c.description(r))}">
<meta name="color-scheme" content="light">
<meta name="theme-color" content="#FE0002">
<meta name="robots" content="noindex">

<meta property="og:type" content="website">
<meta property="og:site_name" content="Number One Travel &amp; Tourism">
<meta property="og:title" content="${esc(c.title(r))} — نمبرون للسفر و السياحة">
<meta property="og:description" content="${esc(c.og(r))}">
<meta property="og:locale" content="ar_SD">
<meta property="og:locale:alternate" content="en_GB">
<meta property="og:url" content="${SITE}${c.dir}/${r.slug}/">
<link rel="canonical" href="${SITE}${c.dir}/${r.slug}/">
<meta property="og:image" content="${SITE}assets/brand/og-image.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="Number One Travel &amp; Tourism">
<meta name="twitter:card" content="summary_large_image">

<link rel="icon" href="assets/brand/favicon-32.png" sizes="32x32" type="image/png">
<link rel="apple-touch-icon" href="assets/brand/apple-touch-icon.png">
<link rel="preload" href="assets/fonts/ibm-plex-sans-arabic-arabic-400.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="assets/fonts/ibm-plex-sans-arabic-arabic-700.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="assets/css/foundation.css">
</head>

<body>
<a class="c-skip-link" href="#main" data-i18n="a11y.skip" data-skip>تخطَّ إلى المحتوى</a>

<div class="l-page">
  <!-- Global header: mounted by the script below. Stage 10.2 -->

  <main id="main" class="l-page__main">
    <section class="l-section c-hero" aria-labelledby="${c.heroLabel}">
      <div class="l-container"><div class="c-hero__grid" data-${c.attr}="hero"></div></div>
    </section>
${c.sections.map((s, i) => `    <section class="l-section${i % 2 === 0 ? ' l-section--subtle' : ''}" data-${c.attr}="${s}" aria-labelledby="${s}-title"${s === 'support' ? ' id="support"' : ''} hidden><div class="l-container" data-${c.attr}-body></div></section>`).join('\n')}
    <section class="l-section l-section--inverse c-cta-band" data-${c.attr}="cta" aria-labelledby="cta-title" hidden>
      <span class="u-numeral-watermark" aria-hidden="true">1</span>
      <div class="l-container" data-${c.attr}-body></div>
    </section>
  </main>

  <!-- Global footer: mounted by the script below. Stage 10.3 -->

  <nav class="c-bottom-nav" aria-label="التنقل السريع" data-i18n-label="nav.quick"><div id="bottom-nav" style="display:contents"></div></nav>
</div>

<script type="module">
  import { boot, el, qs, render, icon, route, pick, mountHeader, mountFooter, ${c.mount}, NAV_BOTTOM }
    from './assets/js/foundation.js';

  // <base> would send href="#main" to the homepage; the skip link scrolls here.
  qs('[data-skip]')?.addEventListener('click', (e) => { e.preventDefault(); const m = qs('#main'); m.tabIndex = -1; m.focus(); m.scrollIntoView(); });

  let ${c.handle} = null;
  function paint() {
    render(qs('#bottom-nav'), NAV_BOTTOM.map((item) =>
      el('a', { class: 'c-bottom-nav__item', href: route(item.href) },
        [icon(item.icon, { size: 'sm' }), el('span', {}, pick(item, 'label'))])));
    ${c.handle} = ${c.mount}({ slug: ${JSON.stringify(r.slug)} });
    window.no = { ...(window.no ?? {}), ${c.handle} };   // QA handle: no.${c.handle}.render('unknown')
  }
  function mountChrome() {
    // The page carries its own final CTA, so the footer's is switched off.
    mountFooter({ target: qs('.l-page'), variant: 'marketing', cta: false });
    mountHeader({ target: qs('.l-page'), current: ${JSON.stringify(c.current)},
      onSearch: () => { window.location.assign(route('book/')); } });
  }
  boot({ sprite: 'assets/icons/sprite.svg', onLocale: () => { mountChrome(); paint(); } });
  mountChrome();
  paint();
</script>
</body>
</html>
`;

let sitemap = readFileSync(join(ROOT, 'sitemap.xml'), 'utf8');
for (const c of COLLECTIONS) {
  const dir = join(ROOT, c.dir);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const wanted = new Set(c.records.map((r) => r.slug));
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory() && !wanted.has(entry.name)) { rmSync(join(dir, entry.name), { recursive: true }); console.log(`removed  ${c.dir}/${entry.name}/`); }
  }
  for (const r of c.records) {
    const out = join(dir, r.slug);
    if (!existsSync(out)) mkdirSync(out, { recursive: true });
    writeFileSync(join(out, 'index.html'), shell(c, r));
    console.log(`written  ${c.dir}/${r.slug}/`);
  }
  const block = c.records.map((r) => `  <url>\n    <loc>${SITE}${c.dir}/${r.slug}/</loc>\n    <lastmod>${TODAY}</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>0.8</priority>\n  </url>`).join('\n');
  const start = `  <!-- ${c.dir}: generated by tools/build-routes.mjs -->`;
  const end = `  <!-- /${c.dir} -->`;
  // migrate the older marker name once
  sitemap = sitemap.replace(`  <!-- ${c.dir}: generated by tools/build-service-pages.mjs -->`, start);
  if (!sitemap.includes(start)) sitemap = sitemap.replace('</urlset>', `${start}\n${end}\n</urlset>`);
  sitemap = sitemap.replace(new RegExp(`${start.replace(/[-/\\^$*+?.()|[\]{}]/g, '\\$&')}[\\s\\S]*?${end.replace(/[-/\\^$*+?.()|[\]{}]/g, '\\$&')}`), `${start}\n${block}\n${end}`);
  console.log(`sitemap  ${c.records.length} ${c.dir} URLs`);
}
writeFileSync(join(ROOT, 'sitemap.xml'), sitemap);
