#!/usr/bin/env node
// Emit assets/js/data/env.js from the process environment — the deployment
// step that turns .env.example's variables into the browser's public config.
// Refuses to write a production file that still points at the development
// adapters or lacks a backend, so a production build cannot ship mock data.
//
//   NO_ENVIRONMENT=production AUTH_PROVIDER=session-api API_BASE_URL=https://api.example/v1 node tools/write-env.mjs
//
// INTEGRATIONS_VERIFIED ({ at, backend, adapters[] }) marks adapters CONNECTED in
// the browser registry. It is honoured ONLY with --verified-by-deploy, which
// tools/deploy.mjs passes after the smoke and acceptance suites have passed
// against the deployed backend — a hand-written value is ignored with a
// warning, so nothing is reported connected merely because its code exists.
import { writeFileSync } from 'node:fs';

const env = process.env;
const json = (name, fallback) => { if (!env[name]) return fallback; try { return JSON.parse(env[name]); } catch { throw new Error(`${name} must be valid JSON`); } };
const FORBIDDEN = /secret|service[_-]?role|private|password|signing|database|db_url|storage_key|stripe_sk|sk_live/i;

const verifiedByDeploy = process.argv.includes('--verified-by-deploy');
const environment = env.NO_ENVIRONMENT ?? 'development';
if (!['development', 'staging', 'production'].includes(environment)) throw new Error(`NO_ENVIRONMENT must be development | staging | production, got ${environment}`);
const authProvider = env.AUTH_PROVIDER ?? 'dev';
if (!['dev', 'session-api'].includes(authProvider)) throw new Error(`AUTH_PROVIDER must be dev | session-api, got ${authProvider}`);
const apiBaseUrl = (env.API_BASE_URL ?? '').replace(/\/+$/, '');
if (environment === 'production') {
  if (authProvider === 'dev') throw new Error('production cannot use the development auth adapter (AUTH_PROVIDER=dev)');
  if (!/^https:\/\//.test(apiBaseUrl)) throw new Error('production needs an https API_BASE_URL');
}
if (apiBaseUrl && !/^https?:\/\//.test(apiBaseUrl)) throw new Error('API_BASE_URL must be an absolute http(s) origin');

const out = {
  environment, authProvider,
  authPublicConfig: json('AUTH_PUBLIC_CONFIG', { sessionRefreshMinutes: 10 }),
  apiBaseUrl,
  documentService: json('DOCUMENT_SERVICE_CONFIG', { maxBytes: 5 * 1024 * 1024, accept: ['application/pdf', 'image/jpeg', 'image/png'] }),
  paymentApi: json('PAYMENT_API_CONFIG', { pageSize: 20 }),
  notifications: json('NOTIFICATION_CONFIG', { refreshOnFocus: true, refreshMinSeconds: 30 }),
  legal: json('LEGAL_DOCUMENT_CONFIG', { source: null, termsPath: null, privacyPath: null }),
  diagnostics: json('DIAGNOSTICS_CONFIG', { endpoint: null }),
  verified: null,
};
if (env.INTEGRATIONS_VERIFIED) {
  if (!verifiedByDeploy) console.warn('INTEGRATIONS_VERIFIED ignored: only tools/deploy.mjs may set it (--verified-by-deploy), after the acceptance run');
  else {
    const v = json('INTEGRATIONS_VERIFIED', null);
    if (!v || !/^\d{4}-\d{2}-\d{2}/.test(v.at ?? '') || v.backend !== apiBaseUrl || !Array.isArray(v.adapters)) throw new Error('INTEGRATIONS_VERIFIED must be { at: ISO date, backend: API_BASE_URL, adapters: [] } for this exact backend');
    if (authProvider !== 'session-api') throw new Error('INTEGRATIONS_VERIFIED needs the production adapters (AUTH_PROVIDER=session-api)');
    out.verified = { at: v.at.slice(0, 10), backend: v.backend, adapters: v.adapters.filter((a) => ['session-api', 'api-customer', 'legal'].includes(a)) };
  }
}
// Nothing that looks like a secret may reach the browser, whatever variable it came from.
const leak = JSON.stringify(out).match(FORBIDDEN);
if (leak) throw new Error(`refusing to write env.js: the public config contains a value that looks like a secret ("${leak[0]}")`);

// ENV_OUT redirects the output (the test suite writes to a temporary file); deployments never set it.
const file = env.ENV_OUT ? new URL(`file://${env.ENV_OUT}`) : new URL('../assets/js/data/env.js', import.meta.url);
writeFileSync(file, `/* GENERATED by tools/write-env.mjs — public runtime configuration. Do not add secrets. */\nexport const ENV = Object.freeze(${JSON.stringify(out, null, 2)});\n\nexport const isProduction = () => ENV.environment === 'production';\n`);
console.log(`env.js written for ${environment} (auth: ${authProvider}, api: ${apiBaseUrl || 'none'}, verified: ${out.verified ? out.verified.adapters.join(',') + ' @ ' + out.verified.at : 'none'})`);
