#!/usr/bin/env node
// Emit assets/js/data/env.js from the process environment — the deployment
// step that turns .env.example's variables into the browser's public config.
// Refuses to write a production file that still points at the development
// adapters or lacks a backend, so a production build cannot ship mock data.
//
//   NO_ENVIRONMENT=production AUTH_PROVIDER=session-api API_BASE_URL=https://api.example/v1 node tools/write-env.mjs
import { writeFileSync } from 'node:fs';

const env = process.env;
const json = (name, fallback) => { if (!env[name]) return fallback; try { return JSON.parse(env[name]); } catch { throw new Error(`${name} must be valid JSON`); } };
const FORBIDDEN = /secret|service[_-]?role|private|password|signing|database|db_url|storage_key|stripe_sk|sk_live/i;

const environment = env.NO_ENVIRONMENT ?? 'development';
if (!['development', 'staging', 'production'].includes(environment)) throw new Error(`NO_ENVIRONMENT must be development | staging | production, got ${environment}`);
const authProvider = env.AUTH_PROVIDER ?? 'dev';
if (!['dev', 'session-api'].includes(authProvider)) throw new Error(`AUTH_PROVIDER must be dev | session-api, got ${authProvider}`);
const apiBaseUrl = (env.API_BASE_URL ?? '').replace(/\/+$/, '');
if (environment === 'production') {
  if (authProvider === 'dev') throw new Error('production cannot use the development auth adapter (AUTH_PROVIDER=dev)');
  if (!/^https:\/\//.test(apiBaseUrl)) throw new Error('production needs an https API_BASE_URL');
}
if (apiBaseUrl && !/^https?:\/\//.test(apiBaseUrl)) throw new Error('API_BASE_URL must be an absolute http(s) origin');

const out = {
  environment, authProvider,
  authPublicConfig: json('AUTH_PUBLIC_CONFIG', { sessionRefreshMinutes: 10 }),
  apiBaseUrl,
  documentService: json('DOCUMENT_SERVICE_CONFIG', { maxBytes: 5 * 1024 * 1024, accept: ['application/pdf', 'image/jpeg', 'image/png'] }),
  paymentApi: json('PAYMENT_API_CONFIG', { pageSize: 20 }),
  notifications: json('NOTIFICATION_CONFIG', { refreshOnFocus: true, refreshMinSeconds: 30 }),
  legal: json('LEGAL_DOCUMENT_CONFIG', { source: null, termsPath: null, privacyPath: null }),
  diagnostics: json('DIAGNOSTICS_CONFIG', { endpoint: null }),
};
// Nothing that looks like a secret may reach the browser, whatever variable it came from.
const leak = JSON.stringify(out).match(FORBIDDEN);
if (leak) throw new Error(`refusing to write env.js: the public config contains a value that looks like a secret ("${leak[0]}")`);

const file = new URL('../assets/js/data/env.js', import.meta.url);
writeFileSync(file, `/* GENERATED by tools/write-env.mjs — public runtime configuration. Do not add secrets. */\nexport const ENV = Object.freeze(${JSON.stringify(out, null, 2)});\n\nexport const isProduction = () => ENV.environment === 'production';\n`);
console.log(`env.js written for ${environment} (auth: ${authProvider}, api: ${apiBaseUrl || 'none'})`);
